plugin:
  name: custom-data-type-tnadiscovery
  version: 2.0
  url: https://github.com/programmfabrik/fylr-plugin-custom-data-type-tnadiscovery
  displayname:
    de-DE: tnadiscovery-Verknüpfung
    en-US: tnadiscovery-Referencing
  info:
    de-DE: Stellt Verknüpfungen mit den Discovery-System des National Archive London her.
    en-US: Use for references to entities of the discoverydystem of the National Archive London.
  l10n: l10n/customDataTypeTNADiscovery.csv
  webfrontend:
    url: customDataTypeTNADiscovery.js
    css: customDataTypeTNADiscovery.css
    dependencies:
      - commons-library
    
base_url_prefix: "webfrontend"

custom_types:
  tnadiscovery:
    mapping:
      conceptName:
        type: text
      conceptURI:
        type: text
      discoveryURL:
        type: text
      referenceNumber:
        type: text
      locationHeld:
        type: text
      title:
        type: text
      description:
        type: text
      facetTerm:
        type: text_l10n
    config:
      schema:
      mask:
        - name: editor_display
          parameters:
            value:
              type: select
              options: ["default", "condensed"]

    update:
      plugin_user:
        reference: system:root
      exec:
        service: "node"
        commands:
          - prog: "node"
            stdin:
              type: body
            stdout:
              type: body
            args:
              - type: "value"
                value: "%_exec.pluginDir%/updater/TNADiscoveryUpdater.js"
              - type: "value"
                value: "%info.json%"
      timeout: 60
      batch_size: 1
      expires_days: 1

base_config:
  - name: update_tnadiscovery
    group: update_custom_data_type
    parameters:
      restrict_time:
        type: bool
        default: false
        position: 0
      from_time:
        type: int
        default: 19
        min: 0
        max: 23
        position: 1
      to_time:
        type: int
        default: 4
        min: 0
        max: 23
        position: 2 